
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y git vim make golang-go apt-transport-https ca-certificates curl software-properties-common iputils-ping curl

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

RUN apt-get update

RUN apt-get install -y docker-ce

RUN apt-get install -y e2fsprogs=1.44.1-1ubuntu1.2
